### ISSUE TITLE
shape: .circle has BUG in SwiftUI and iOS 15

### ISSUE THREAD

**Issue by c941010623** [michael94ellis/SwiftUIJoystick#1]
when use

```
JoystickBuilder(
                monitor: self.joystickMonitor,
                width: self.dragDiameter,
                shape: .circle,
                background: {
                    Circle().fill(Color.blue.opacity(0.9))
                        .frame(width: dragDiameter, height: dragDiameter)
                },
                foreground: {
                    Circle().fill(Color.black)
                        .frame(width: dragDiameter / 4, height: dragDiameter / 4)
                },
                locksInPlace: false)
```

then then location point is error

**Comment by michael94ellis** [comment]
I apologize for the error, you should be able to use the square version or the .rect

I appreciate your bug report and will add it to my todo list. I personally just used rect 

Can you tell me how you are using this framework? I adjusted it to meet the needs of a specific project I made but I could make it more flexible

**Comment by c941010623** [comment]
Your project is quite perfect,
I use it in Google Map and use the joystick to control the movement of the map, which has achieved the effect of moving characters.

At present, I want the joystick to be circular, similar to the operation of the general game, and I am looking forward to your correction.

The project environment I use is Xcode 13 and SwiftUI and iOS 15

**Comment by c941010623** [comment]
I found that your Initial Release v1.0.3 ~ v1.4.0 works perfectly without any bugs

Bugs since > v1.4.0

You can compare the differences to make the new version better

**Comment by c941010623** [comment]
I Fixed that, please check it

**Comment by michael94ellis** [comment]
Hey, I updated the podspec and the SPM spec, so you should be able to update now. I also made a small change and implemented a new CGPoint + operator, so please respond back if anything unexpected happens! Thanks so much
