### ISSUE TITLE
Multi-touch interference

### ISSUE THREAD

**Issue by c941010623** [michael94ellis/SwiftUIJoystick#3]
When I use the Demo,

I hold the left hand with my left hand and click on the rectangle with my right hand,

then the center point will stop.

summary:
If there is a click event in the rectangle while moving, the center point will stop.

**Comment by c941010623** [comment]
I Fixed that, please check it

**Comment by michael94ellis** [comment]
Hey, I really appreciate your contributions! I have been out of town for last few days and will become available again on Friday.
