### ISSUE TITLE
Can't add Swift Package on GUI

### ISSUE THREAD

**Issue by crane-hiromu** [michael94ellis/SwiftUIJoystick#5]
We can search but we can't add.

![Screen Shot 2022-09-25 at 15 35 09](https://user-images.githubusercontent.com/24838521/192131481-22cd53c1-4038-4e5d-a146-29c6759a7688.png)

<bt>

It can be added by writing directly in the package file.

```
.package(url: "https://github.com/michael94ellis/SwiftUIJoystick", "1.5.0"..<"2.0.0")
```

<br>

Release tag is stopped on an older version.

![Screen Shot 2022-09-25 at 15 41 19](https://user-images.githubusercontent.com/24838521/192131656-41e638ff-9de1-45fa-8927-dd61c3aa9dfd.png)

Please add the newest release tag on your github :)

**Comment by michael94ellis** [comment]
I see you have the main branch as your source in that first image, did you
try specifying a version?

**Comment by michael94ellis** [comment]
<img width="1061" alt="Screenshot 2023-09-26 at 9 14 26 PM" src="https://github.com/michael94ellis/SwiftUIJoystick/assets/25714232/c144f572-2b15-4a30-9ca3-23db3f50dbb3">

**Comment by michael94ellis** [comment]
I was checking and updating this package and noticed I could not reproduce the issue. Let me know if you're still having trouble
